### ISSUE TITLE
api-mode: never reject any browser request

### ISSUE THREAD

**Issue by radiospiel** [jdesrosiers/sinatra-cors#5]
for generic API-style services it would be helpful to provide a method which configures Sinatra::CORS in a way which allows all origins, methods, and headers. This would be useful for any service, which by intention exposes their API to all websites that want to use that.

I am not 100% sure if this would basically be 

    set :allow_origin, "*"

**Comment by jdesrosiers** [comment]
Thanks for the suggestion. I've put some thought into this and I've decided that such an option doesn't fit with the secure-by-default approach this library takes. I designed this library to make everything restricted by default and to guide you through setting things up properly with helpful messages in the logs. Although useful in some cases, adding an option that allows everything goes against the grain of that approach.

If you choose to fork and do it yourself, it should be pretty easy. Most of it would just require reflecting data passed in request headers to the response headers.

* `Origin` => `Access-Control-Allow-Origin`
* `Access-Control-Request-Method` => `Access-Control-Allow-Methods`
* `Access-Control-Request-Headers` => `Access-Control-Allow-Headers`

You can hardcode `Access-Control-Allow-Credentials: true`.

`Access-Control-Expose-Headers` is the only one you'll need to do some computation for. Get a list of all the response headers for the request. Remove any of: `Cache-Control`, `Content-Language`, `Content-Length`, `Content-Type`, `Expires`, `Last-Modified`, `Pragma`. Then set those to `Access-Control-Expose-Headers` as a comma separated list.

That would unlock all of the door CORS closes.

**Comment by radiospiel** [comment]
@jdesrosiers thank you for your feedback.
