### ISSUE TITLE
Have not been able to get CORS working in small test application.

### ISSUE THREAD

**Issue by marvfinsy** [jdesrosiers/sinatra-cors#7]
As best as i can see there is a method that has the following code:

        settings.routes.each do |method, routes| do ... ... ...

In my situation routes is always empty...

Here is how i am attempting to configure:

module Api
  class ApiRoot < Sinatra::Base
    register Sinatra::Cors

    configure do
      set :logging, true
      set :raise_errors, false
      set :show_exceptions, false
      set :json_encoder, Oj.mimic_JSON
      set :default_content_type, 'application/json'
      logger = Logger.new(STDOUT)
      logger.level = ENV.fetch('API_LOG_LEVEL', '1').to_i
      set :logger, logger

      set :allow_origin, "*"
      set :allow_methods, "GET,POST,PATCH,OPTIONS"
      set :allow_headers, "content-type,accept,if-modified-since"
      set :expose_headers, "location,link"
    end
    # routes start here#
  end
end

Any ideas on what i'm doing wrong? thx...

Marvin...   marvinfoster@finsync.com  or mmarvb7@gmail.com

**Comment by jdesrosiers** [comment]
There doesn't seem to be any problem with the code you've shared. If you have a more complete example you can share, I might be able to help you debug further.

**Comment by marvfinsy** [comment]
hi thx for the response...
i decided upon a slightly different direction.
while i understand why the code enumerate through the routes, i didn't want to take the performance hit for each CORS preflight call. using yours and another CORS gem i found as inspiration, i came up with my own implementation.
1. It does not iterate through the route collections.
2. i do not install the after-filter. The user adds their own before or after filter and calls the cors_handler method.
3. I modified things such that it can be used in a before or after filter.
In my current use i prefer to use it in a before-filter.

Note i have linked ur repo in the code. Hope that is ok.
Thx again... 
~Marvin

**Comment by jdesrosiers** [comment]
Glad you found a solution that works for you.
